### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by uncomfyhalomacro** [Firstyear/vulkano-experiment#1]
**OS**: OpenSUSE TumbleWeed
**Kernel Version**: 5.16.11-1-default
**CPU**: Intel i5-10300H (8) @ 4.500GHz 
**GPU**:  NVIDIA GeForce RTX 3060 Mobile / Max-Q 
**Rust/Cargo Version**: cargo 1.61.0-nightly (3d6970d 2022-02-28)

**Expected Behavior**
Well, Idk maybe something amazing pops up like a graphic thingy

**Actual Behavior**
Nothing happens. Just panics.

**Relevant Information**

```sh
RUST_BACKTRACE=full cargo run --release --verbose   
       Fresh unicode-xid v0.2.2
       Fresh autocfg v1.1.0
       Fresh cfg-if v1.0.0
       Fresh itoa v1.0.1
       Fresh xml-rs v0.8.4
       Fresh ryu v1.0.9
       Fresh regex-syntax v0.6.25
       Fresh hashbrown v0.11.2
       Fresh heck v0.4.0
       Fresh cc v1.0.73
       Fresh lazy_static v1.4.0
       Fresh scopeguard v1.1.0
       Fresh smallvec v1.8.0
       Fresh half v1.8.2
       Fresh fnv v1.0.7
       Fresh vk-parse v0.7.0
       Fresh instant v0.1.12
       Fresh libloading v0.7.3
       Fresh cmake v0.1.48
       Fresh lock_api v0.4.6
       Fresh proc-macro2 v1.0.36
       Fresh libc v0.2.119
       Fresh memchr v2.4.1
       Fresh crossbeam-utils v0.8.7
       Fresh quote v1.0.15
       Fresh ash v0.35.2+1.2.203
       Fresh syn v1.0.86
       Fresh aho-corasick v0.7.18
       Fresh indexmap v1.8.0
       Fresh parking_lot_core v0.8.5
       Fresh shared_library v0.1.9
       Fresh crossbeam-queue v0.3.4
       Fresh serde_derive v1.0.136
       Fresh regex v1.5.5
       Fresh shaderc-sys v0.7.4
       Fresh parking_lot v0.11.2
       Fresh serde v1.0.136
       Fresh shaderc v0.7.4
       Fresh serde_json v1.0.79
       Fresh vulkano v0.28.0
       Fresh vulkano-shaders v0.28.0
       Fresh vulkano-experiment v0.1.0 (/home/uncomfy/Projects/vulkano-experiment)
warning: unused variable: `builder`
  --> src/main.rs:64:17
   |
64 |         let mut builder = AutoCommandBufferBuilder::primary(
   |                 ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_builder`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
  --> src/main.rs:64:13
   |
64 |         let mut builder = AutoCommandBufferBuilder::primary(
   |             ----^^^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: `vulkano-experiment` (bin "vulkano-experiment") generated 2 warnings
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/vulkano-experiment`
Device -> NVIDIA GeForce RTX 3060 Laptop GPU, ACU -> None, DID -> 9504, MBS -> Some(18446744073709486080)
thread 'main' panicked at 'failed to create device: ExtensionRestrictionNotMet(ExtensionRestrictionError { extension: "khr_portability_subset", restriction: NotSupported })', src/main.rs:51:10
stack backtrace:
   0:     0x55cfa15b018c - std::backtrace_rs::backtrace::libunwind::trace::h6ac5130eed1dcf9f
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cfa15b018c - std::backtrace_rs::backtrace::trace_unsynchronized::h2b7158a3e8f3af61
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cfa15b018c - std::sys_common::backtrace::_print_fmt::h75f85af0fdb05879
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55cfa15b018c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5f37961d0a32553a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55cfa15cee0c - core::fmt::write::h29046f193433d2f3
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/fmt/mod.rs:1190:17
   5:     0x55cfa15ad641 - std::io::Write::write_fmt::h85f676fd3a2afd23
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/io/mod.rs:1655:15
   6:     0x55cfa15b1a65 - std::sys_common::backtrace::_print::h79369394439142a7
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55cfa15b1a65 - std::sys_common::backtrace::print::h358c3300488d298b
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55cfa15b1a65 - std::panicking::default_hook::{{closure}}::hbbc54c317f78453b
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:295:22
   9:     0x55cfa15b1708 - std::panicking::default_hook::he69a91523cadf6a8
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:314:9
  10:     0x55cfa15b1fb3 - std::panicking::rust_panic_with_hook::h88c443d0811b5ee8
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:698:17
  11:     0x55cfa15b1e97 - std::panicking::begin_panic_handler::{{closure}}::hf0e3adb08d6f840d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:588:13
  12:     0x55cfa15b0644 - std::sys_common::backtrace::__rust_end_short_backtrace::h876fe414bbc74075
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55cfa15b1bc9 - rust_begin_unwind
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:584:5
  14:     0x55cfa14bf093 - core::panicking::panic_fmt::hb2c11159edd998a3
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/panicking.rs:143:14
  15:     0x55cfa14bf183 - core::result::unwrap_failed::hd4f8fd644547ed9d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/result.rs:1784:5
  16:     0x55cfa14d838e - vulkano_experiment::main::h1385783b9fbfb803
  17:     0x55cfa14f62b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a5b82daf8bbed52
  18:     0x55cfa14cdaf9 - std::rt::lang_start::{{closure}}::h111d586966e5eb75
  19:     0x55cfa15af91b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb45fb6e5d6b3737a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/ops/function.rs:259:13
  20:     0x55cfa15af91b - std::panicking::try::do_call::he5037ad1eb203c16
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:492:40
  21:     0x55cfa15af91b - std::panicking::try::h2a41162a6dbb922a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:456:19
  22:     0x55cfa15af91b - std::panic::catch_unwind::h7ba3515aecd46d8e
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panic.rs:137:14
  23:     0x55cfa15af91b - std::rt::lang_start_internal::{{closure}}::h42b423f0d606139d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/rt.rs:128:48
  24:     0x55cfa15af91b - std::panicking::try::do_call::hc070550b805bf778
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:492:40
  25:     0x55cfa15af91b - std::panicking::try::heb8a086d3eda308a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:456:19
  26:     0x55cfa15af91b - std::panic::catch_unwind::h36cd43754cc229ee
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panic.rs:137:14
  27:     0x55cfa15af91b - std::rt::lang_start_internal::h8d843bd59d61a4e9
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/rt.rs:128:20
  28:     0x55cfa14d9fc2 - main
  29:     0x7f7fa7d0d630 - __libc_start_call_main
  30:     0x7f7fa7d0d6f0 - __libc_start_main_alias_1
  31:     0x55cfa14bf875 - _start
                               at /home/abuild/rpmbuild/BUILD/glibc-2.35/csu/../sysdeps/x86_64/start.S:115
  32:                0x0 - <unknown>
  ```

**Comment by Firstyear** [comment]
Can you set this line to false and try again? 

https://github.com/Firstyear/vulkano-experiment/blob/main/src/main.rs#L46

**Comment by uncomfyhalomacro** [comment]
> Can you set this line to false and try again?
> 
> https://github.com/Firstyear/vulkano-experiment/blob/main/src/main.rs#L46

```
RUST_BACKTRACE=full cargo run --release --verbose
       Fresh unicode-xid v0.2.2
       Fresh autocfg v1.1.0
       Fresh cfg-if v1.0.0
       Fresh regex-syntax v0.6.25
       Fresh xml-rs v0.8.4
       Fresh hashbrown v0.11.2
       Fresh itoa v1.0.1
       Fresh ryu v1.0.9
       Fresh cc v1.0.73
       Fresh heck v0.4.0
       Fresh lazy_static v1.4.0
       Fresh scopeguard v1.1.0
       Fresh smallvec v1.8.0
       Fresh fnv v1.0.7
       Fresh half v1.8.2
       Fresh vk-parse v0.7.0
       Fresh instant v0.1.12
       Fresh libloading v0.7.3
       Fresh cmake v0.1.48
       Fresh lock_api v0.4.6
       Fresh proc-macro2 v1.0.36
       Fresh libc v0.2.119
       Fresh memchr v2.4.1
       Fresh crossbeam-utils v0.8.7
       Fresh quote v1.0.15
       Fresh ash v0.35.2+1.2.203
       Fresh syn v1.0.86
       Fresh aho-corasick v0.7.18
       Fresh indexmap v1.8.0
       Fresh parking_lot_core v0.8.5
       Fresh crossbeam-queue v0.3.4
       Fresh shared_library v0.1.9
       Fresh serde_derive v1.0.136
       Fresh regex v1.5.5
       Fresh shaderc-sys v0.7.4
       Fresh parking_lot v0.11.2
       Fresh serde v1.0.136
       Fresh shaderc v0.7.4
       Fresh serde_json v1.0.79
       Fresh vulkano v0.28.0
       Fresh vulkano-shaders v0.28.0
       Fresh vulkano-experiment v0.1.0 (/home/uncomfy/Projects/vulkano-experiment)
warning: unused variable: `builder`
  --> src/main.rs:64:17
   |
64 |         let mut builder = AutoCommandBufferBuilder::primary(
   |                 ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_builder`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
  --> src/main.rs:64:13
   |
64 |         let mut builder = AutoCommandBufferBuilder::primary(
   |             ----^^^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: `vulkano-experiment` (bin "vulkano-experiment") generated 2 warnings
    Finished release [optimized] target(s) in 0.01s
     Running `./vulkano-experiment`
Device -> NVIDIA GeForce RTX 3060 Laptop GPU, ACU -> None, DID -> 9504, MBS -> Some(18446744073709486080)
1 queue(s) available
Immuted buffer is ready!
Took - 1.520077ms
Took - 13.781µs
Everything succeeded!
```
Is this the intended behavior?

**Comment by Firstyear** [comment]
My card required it to be true else it wouldn't run - you're clearly needs it to be false. It's annoying :(
